### ISSUE TITLE
mgread for files outside search path

### ISSUE THREAD

**Issue by krisny** [benlyyan/MGT#16]
The mgread function requires audio and video files to be within the working directory or the search path. 
I think this can be fixed in lines 26 and 32 of mgread by including the path in the file specification. Something like this:
        mg = mgvideoreader([path, file]);

**Comment by benlyyan** [comment]
This is really good point. I will add that.

**Comment by benlyyan** [comment]
The mgread and mgread1 have been updated so that they can read data outside of current path.
