### ISSUE TITLE
mgvideocrop - three issues

### ISSUE THREAD

**Issue by krisny** [benlyyan/MGT#18]
1) I think it would be good if there was instructions to the user to select a cropping frame and double click to end the selection procedure. Maybe a printout in the command window.

2) I had some trouble getting the pos argument to work. The help file should probably specify with an example:
`croppedvideo = mgvideocrop(d,[20 40 30 50])`

3) When specifying file name like this
croppedvideo = mgvideocrop(d,[20 40 30 50],'newfilename')
I get the following output:

> ***_cropping video**_*
> process in progress:100%
> Error using VideoReader/init (line 607)
> The filename specified was not found in the MATLAB path.
> 
> Error in VideoReader (line 172)
>             obj.init(fileName);
> 
> Error in mgvideoreader (line 27)
>     obj = VideoReader(fn);
> 
> Error in mgvideocrop (line 110)
>     s = mgvideoreader(filename);

**Comment by benlyyan** [comment]
I guess the given filename should be 'newfilename.avi' .    Writer needs the file extension.
