### ISSUE TITLE
mgvideoadjust - column/row for contrast adjustment

### ISSUE THREAD

**Issue by krisny** [benlyyan/MGT#19]
I really like that mgvideoadjust provides the possibility to adjust separately for RGB colors. However, when used only with a single value for lo_in hi_in and lo_out hi_out, it would be nice if the user could choose whether to input as row- or column vectors. 
E.g. this:
`mgvideoadjust(d,[.4; .6],[0; 1])`
and this:
`mgvideoadjust(d,[.4, .6],[0, 1])`
would be the same.

**Comment by benlyyan** [comment]
I think it should be the same in both cases. The function does not care the row or colum

**Comment by benlyyan** [comment]
Sorry, the first one should be correct. The second one works wrong.

**Comment by benlyyan** [comment]
Now it works in both cases. It does not care row or column
