### ISSUE TITLE
Problem with mgread

### ISSUE THREAD

**Issue by alexarje** [benlyyan/MGT#2]
@benlyyan #bug

Trying to load a video file: 

```
>> mg=mgread('dance.mp4')
Output argument "mg" (and maybe others) not assigned during call to "mgread".
```

Also tried to run 

```
>> mg=mginitstruct
```

but same problem.

**Comment by alexarje** [comment]
One more problem: 

```
>> mgread('Video')
please select a video file .mp4,.m4v,.mpg,.mov,.avi
Error using VideoReader/init (line 619)
Could not read file due to an unexpected error. Reason: Unable to initialize the video obtain properties

Error in VideoReader (line 172)
            obj.init(fileName);

Error in mgvideoreader (line 29)
    obj = VideoReader(fn);

Error in mgread (line 32)
        mg = mgvideoreader(file);
```

**Comment by benlyyan** [comment]
​I guess Matlab 2016 has changed some perporties of videoreader object. So it causes often the same error when initiate  a video object.  I will try that in Matlab 2016.

**Comment by krisny** [comment]
I agree on ARJ's first comment here that it would be nice if it was possible to use mgread(filename), or maybe mgread(typestring, filename) makes the implementation easier.

**Comment by benlyyan** [comment]
I think if we want input video,audio,motion data at the same time, it will be more conveninent.

**Comment by benlyyan** [comment]
I add one function mgread1 in source code folder, which works like mg = mgread(videofile), mg = mgread(videofile,audiofile,mocapfile),etc.
