### ISSUE TITLE
missing progmeter

### ISSUE THREAD

**Issue by krisny** [benlyyan/MGT#23]
I get this when running the mgdemo1. Seems that the progmeter function is missing.

Undefined function or variable 'progmeter'.

Error in mgmotion (line 313)
            progmeter(ind,numf);

Error in mgdemo1 (line 28)
mgsegmo = mgmotion(mgseg,'Diff');

**Comment by benlyyan** [comment]
Yes, I add it to source code. It should be included in MGT.zip as well.

**Comment by krisny** [comment]
Great. I cloned the repo, so that's why I didn't get it
