### ISSUE TITLE
Audio loads as video

### ISSUE THREAD

**Issue by alexarje** [benlyyan/MGT#4]
Looks like importing only audio loads it in the video field?

```
>> mg=mgvideoreader('pianist.wav')

mg = 

         video: [1x1 struct]
          type: 'mg data'
    createtime: '09-Jun-2016'

>> mgwaveplot(mg)
Reference to non-existent field 'audio'.

Error in mgwaveplot (line 15)
audio = varargin{1}.audio.mir

```

Shouldn't it either give an error message or try to load it in the audio field?

**Comment by benlyyan** [comment]
It will only read video file.I fixed the error message if the video file is not given.
