### ISSUE TITLE
Average video and average motion video

### ISSUE THREAD

**Issue by alexarje** [benlyyan/MGT#6]
# request

It would be cool to have functions for creating average videos (mean of all frames) for 
1. both regular and motion images
2. in both colour and greyscale
3. in both regular and inverted mode

**Comment by benlyyan** [comment]
I try to write a function mgmotionhistory to create motion history. You can find it in source code folder.

**Comment by benlyyan** [comment]
The function mgvideoaverage has been added to source code folder working in both color and gray scale.
