### ISSUE TITLE
Weird counting from mgmotion

### ISSUE THREAD

**Issue by alexarje** [benlyyan/MGT#8]
It is great to have the counting working in mgmotion, but could it be on its own line? Now it truncates the same line as the command, see screenshot for how it looks (on 2015b on OSX).

Example 1: 

![screen shot 2016-06-10 at 13 09 04](https://cloud.githubusercontent.com/assets/114316/15962642/d61c3668-2f0c-11e6-9805-32d430241606.png)

Example 2: 

![screen shot 2016-06-10 at 13 32 13](https://cloud.githubusercontent.com/assets/114316/15963093/90b922fe-2f0f-11e6-827e-a98d8a308d4f.png)

**Comment by benlyyan** [comment]
It's really weird. I run it on my computer. It was ok.
![qq 20160612181855](https://cloud.githubusercontent.com/assets/8624410/15990606/237027e4-30ca-11e6-9fa8-1c2f20e1e6c0.png)
